default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
      scan(
        project: "IceAndFire/IceAndFire.xcodeproj",
        scheme: "IceAndFire",
        devices: ["iPhone 14"])
  end
end
